urlshortener/shortenersite/urls.py
from django.conf.urls import url,include
from .views import index ,about,contact, redirect_original ,shorten_url 

urlpatterns = [
	url(r'^$', index , name='home'),
    # for our home/index page
 
    url(r'^(?P<short_id>[\w]{6})$', redirect_original , name='redirectoriginal'),
    # when short URL is requested it redirects to original URL
 	url(r'^about/$', about, name='about'),
 	url(r'^contact/$', contact, name='contact'),
    url(r'^makeshort/$', shorten_url, name='shortenurl'),
 
]

urlshortener/urlshortener/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('shortenersite.urls',namespace='shortenersite')),
]

urlshortener/shortenersite/models.py
from django.db import models
import string,random

# Create your models here.
 
# Create your models here.
class Urls(models.Model):
	short_id = models.SlugField(max_length=6,primary_key=True)
	httpurl = models.URLField(max_length=200)
	pub_date = models.DateTimeField(auto_now=True)
	count = models.IntegerField(default=0)

	def makeshort():
		length = 6
		char = string.ascii_uppercase + string.digits + string.ascii_lowercase
		# if the randomly generated short_id is used then generate next
		while True:
			short_id = ''.join(random.choice(char) for x in range(length))
			try:
				temp = Urls.objects.get(pk=short_id)
			except:
				return short_id

	def __str__(self):
		return self.httpurl

urlshortener/shortenersite/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect,HttpResponseRedirect,Http404
from django.core.validators import URLValidator
from .models import Urls

# Create your views here.

def index(request):
	return render(request,"index.html",context={})

def about(request):
	return render(request,"about.html",context={})

def contact(request):
	return render(request,"contact.html",context={})




def redirect_original(request,short_id):

	
	if(Urls.objects.filter(short_id=short_id).exists()):
		obj=Urls.objects.filter(short_id=short_id)[0]
		obj.count+=1
		obj.save()
		return HttpResponseRedirect(obj.httpurl)

	else:
		raise Http404("Given Link Does Not Exist :(") 


def shorten_url(request):
	SITE_URL = "http://localhost:8000/"
	context={}
	url=request.POST.get("url")
	ob=URLValidator()
	try:
		ob(url)
		if(Urls.objects.filter(httpurl=url).exists()):
			# context['exists']='exist'
			short_id=Urls.objects.filter(httpurl=url)[0].short_id
			return render(request,"index.html",context={'short_id':SITE_URL+short_id,'exists':True})
		else:
			short_url=Urls.makeshort()
			newob=Urls.objects.create(httpurl=url,short_id=short_url)
			return render(request,"index.html",context={'short_id':SITE_URL+short_url})
	except:
		return render(request,"index.html",context={'notvalid':'notvalid'})

urlshortener/templates/about.html
{% include 'base.html' %}

<br><br>
<div class="container">
{% include 'snippets/nav.html' %}
<br><br>
<div class = "panel panel-success">
   <div class = "panel-heading">
      <h3 class = "panel-title">ABOUT US</h3><hr>
   </div>
   <br>
   <div class = "panel-body">
      UNLEASH THE POWER OF THE LINK.<br>
      GET RID OF LONG AND UGLY LINKS.<br>
The link is the invisible thread that connects every customer interaction to tell a greater story. Drive seamless experiences across every channel and every device with this url shotener.
   </div>
</div>	

</div>

urlshortener/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title_content %} URLShortener {% endblock title_content %}  </title>
	{% include "snippets/css.html" %}
</head>
<body>
	<div class="container">
	 <div class="jumbotron">
	<h1>URL Shortener</h1>
</div>
</div>
	{%block content%}
	
	{%endblock content%}



</body>
{% include "snippets/js.html" %}
</html>

urlshortener/templates/contact.html
{% include 'base.html' %}

<br><br>
<div class="container">
{% include 'snippets/nav.html' %}
<div class = "panel panel-success">
   <div class = "panel-heading">
      <h3 class = "panel-title">CONTACT US</h3><hr>
   </div>
   <br>
   <div class = "panel-body">
      phone : +918860556375<br>
      TWITTER : <a href="https://twitter.com/k_nitzz23">Nitesh</a><br>

   </div>
</div>	

</div>

urlshortener/templates/index.html
{% include 'base.html' %}
{% block content %}
<div class="container">
	<br><br>
	{% include 'snippets/nav.html' %}
	<br>

 <div class="card">
 	<form class="col-sm-9 "method="post" action="{% url 'shortenersite:shortenurl' %}">
		 <input style="padding:20px ;margin:10px" type="text" name="url" id="url" class="form-control input-sm" placeholder="type a url" />
		 
		  {% csrf_token %}
		 <button type="submit" id="submitButton" class="btn btn-primary">Submit</button></p> 
	 </form>


 
<span id="url-result">Enter the URL above and click submit!</span>
{% if notvalid %}
</div>
<div><p>NOT A VALID URL</p></div>



{% endif %}

{% if short_id %}
  <div class="panel panel-success">
      <div class="panel-heading">Short Url Generated !!</div>
      <div class="panel-body"><a href="{{ short_id }}">{{ short_id }}</a></div>
    </div>



{% endif %}
</div>

{% endblock %}

urlshortener/templates/snippets/css.html
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
 

urlshortener/templates/snippets/js.html
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

urlshortener/templates/snippets/nav.html
<!-- A grey horizontal navbar that becomes vertical on small screens -->
<nav class="navbar navbar-expand-sm bg-light">

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href='{% url "shortenersite:home" %}'>Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href='{% url "shortenersite:contact" %}'>Contact</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href='{% url "shortenersite:about" %}'>About</a>
    </li>
   
  </ul>

</nav>